In [1]:
import os
import glob
import numpy as np

data_path = '/home/jabblee/Desktop/CRC_collections/CRC_origin/data/npy/'
data_path_lst = glob.glob(data_path + '*', recursive = True)

print('Total npy file cnts :', len(data_path_lst))

Total npy file cnts : 9842


In [2]:
sample_data_path = data_path_lst[0]

sample_data_load = np.load(sample_data_path)
print(sample_data_load.shape)
print(sample_data_load)

(15, 7)
[[  86 3639 3778 3701 3714 3661    0]
 [  87 3686 3795 3699 3708 3665    0]
 [  88 3641 3772 3693 3693 3632    0]
 [  89 1841 1856 3609 3717 3683    6]
 [  90 1663 1813 3568 3697 3659    6]
 [  91 1701 1798 3569 3696 3664    6]
 [  92 1941 2715 2551 2053 3603   12]
 [  93 2145 2434 2559 1917 3522   12]
 [  94 2223 2377 2559 1909 3513   12]
 [  95 2263 3713 3611 3250 3638    4]
 [  96 1823 3759 3692 3710 3622    4]
 [  97 1808 3757 3702 3702 3604    4]
 [  98 1717 3760 3697 3709 3600    4]
 [  99 1793 3760 3715 3711 3628    4]
 [ 100 3548 3782 3696 3706 3637    0]]


In [3]:
for data in data_lst:
    data_arr = np.load(data)
    print('data ndarray Shape :', data_arr.shape)

data ndarray Shape : (15, 7)
data ndarray Shape : (12, 7)
data ndarray Shape : (9, 7)
data ndarray Shape : (15, 7)
data ndarray Shape : (11, 7)
data ndarray Shape : (14, 7)
data ndarray Shape : (14, 7)
data ndarray Shape : (13, 7)
data ndarray Shape : (24, 7)
data ndarray Shape : (11, 7)
data ndarray Shape : (14, 7)
data ndarray Shape : (13, 7)
data ndarray Shape : (11, 7)
data ndarray Shape : (14, 7)
data ndarray Shape : (13, 7)
data ndarray Shape : (19, 7)
data ndarray Shape : (15, 7)
data ndarray Shape : (17, 7)
data ndarray Shape : (23, 7)
data ndarray Shape : (15, 7)
data ndarray Shape : (14, 7)
data ndarray Shape : (16, 7)
data ndarray Shape : (14, 7)
data ndarray Shape : (12, 7)
data ndarray Shape : (14, 7)
data ndarray Shape : (11, 7)
data ndarray Shape : (13, 7)
data ndarray Shape : (19, 7)
data ndarray Shape : (15, 7)
data ndarray Shape : (14, 7)
data ndarray Shape : (17, 7)
data ndarray Shape : (15, 7)
data ndarray Shape : (23, 7)
data ndarray Shape : (22, 7)
data ndarray Sh

In [4]:
import os
import glob
import numpy as np

train_data_path = '/home/jabblee/Desktop/CRC_collections/CRC_update/2023_Gatherings/TRAIN/'
test_data_path = '/home/jabblee/Desktop/CRC_collections/CRC_update/2023_Gatherings/TEST/'
train_data_paths_lst = glob.glob(train_data_path + '*', recursive = True)
test_data_paths_lst = glob.glob(test_data_path + '*', recursive = True)

print('Total train npy file cnts :', len(train_data_paths_lst))
print('Total test npy file cnts :', len(test_data_paths_lst))

Total train npy file cnts : 264
Total test npy file cnts : 264


In [3]:
train_sample = train_data_paths_lst[0]
test_sample = test_data_paths_lst[0]
train_sample_np = np.load(train_sample, allow_pickle = True)
print(train_sample_np.shape)
test_sample_np = np.load(test_sample, allow_pickle = True)
print(test_sample_np.shape)

(40, 9)
(40, 9)
